### ISSUE TITLE
if Rulers (Ctrl+R) - ON. - movement in X,Y is wrong

### ISSUE THREAD

**Issue by Evgenw** [chuanqisun/figma-plugin-spacemouse#12] opened 2022-11-19 14:50 UTC
if Rulers (Ctrl+R) - ON. - movement in X,Y is wrong. For example, if I press to the right, the space shifts down-to the right, approximately an angle of 45.
Thanks :)

**Comment by chuanqisun** [comment] 2022-12-12 18:06
Confirmed! I've been puzzled by this for a long time and thought something is broken with my setup, so thank you for digging up the root cause.

It turns out Figma [viewport API](https://www.figma.com/plugin-docs/api/figma-viewport) does not handle the ruler correctly. It will drift. I'm filing a bug towards Figma API.

UPDATE, issue tracked on Figma developer forum: https://forum.figma.com/t/viewport-center-is-inaccurate-when-ruler-is-on/34757

**Comment by chuanqisun** [comment] 2023-01-19 06:08
Good news @Evgenw. This is fixed by the Figma development team.

**Closed as completed by chuanqisun** 2023-01-19 06:08 UTC
Labels: figma

**Comment by Evgenw** [comment] 2023-01-24 08:30
Thank you so much!
