### ISSUE TITLE
After updating figma to app-108.1.0 - 3dconnexion began to work jerky

### ISSUE THREAD

**Issue by Evgenw** [chuanqisun/figma-plugin-spacemouse#10] opened 2022-03-22 14:24 UTC
Hello, my friend!
Something terrible happened :(

After updating figma to app-108.1.0 - 3d began to work jerkily and was not possible to use.
 
I made a backup of app-107.1.0 and everything works fine in it, but I'm afraid that sooner or later I'll have to update.

Can make normal 3dconnexion work in app-108.1.0 or later

Thank you very much!

**Comment by chuanqisun** [comment] 2022-11-06 04:44
Hey Evgenw, does the issue still exist? I can't reproduce it in my environment (version 116). Closing for now but feel free to re-open.

**Closed as completed by chuanqisun** 2022-11-06 04:44 UTC
